# Generated by Django 3.1.3 on 2020-11-14 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("member", "0001_initial"),
        ("tour", "0001_initial"),
        ("supplier", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScoreBaseLog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("category", models.IntegerField()),
                ("food_score", models.CharField(max_length=256)),
                ("traffic_score", models.CharField(max_length=256)),
                ("scheduler_score", models.CharField(max_length=256)),
                ("tour_guide_score", models.CharField(max_length=256)),
                ("stay_score", models.CharField(max_length=256)),
                ("description", models.CharField(max_length=2048)),
                ("member", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="member.memberbase")),
                (
                    "supplier",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="supplier.supplierbase"),
                ),
                ("tour_group", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tour.tourgroupbase")),
            ],
            options={
                "db_table": "score_base_log",
            },
        ),
    ]
