version: "3"

networks:
  net:
    driver: bridge

services:
  db:
    container_name: tripresso_local
    build:
      context: .
      dockerfile: ./dockerfile/mysql.dockerfile
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - net

  web:
    container_name: tripresso_be
    build:
      context: .
      dockerfile: ./dockerfile/tripresso.dockerfile
    environment:
      - BUILD_ENV=local
    command: bash -c "
        ./wait-for-it.sh db:3306 &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "
    ports:  
      - 8000:8000  
    depends_on:
      - db
    networks:
      - net
