# Generated by Django 3.1.3 on 2020-11-10 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
        ('supplier', '0002_add_model')
    ]

    operations = [
        migrations.CreateModel(
            name='TourGroupLocation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.IntegerField()),
                ('option', models.IntegerField()),
                ('tour_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.tourgroupbase')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
