# Generated by Django 3.1.3 on 2020-11-14 09:47

import core.constants
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tour", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberBase",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False
                    ),
                ),
                ("platform", models.IntegerField(default=core.constants.PlatformType["TRIPRESSO"])),
                ("account", models.CharField(max_length=256)),
                ("surname", models.CharField(max_length=256)),
                ("given_name", models.CharField(max_length=256)),
                ("gender", models.IntegerField(default=0)),
                ("birthday", models.DateField()),
                ("email", models.CharField(max_length=256)),
                ("phone", models.CharField(max_length=256)),
                ("address", models.CharField(max_length=256)),
                ("tripresso_coin", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "member_base",
            },
        ),
        migrations.CreateModel(
            name="MemberFavorite",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False
                    ),
                ),
                ("member", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="member.memberbase")),
                ("tour_group", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tour.tourgroupbase")),
            ],
            options={
                "db_table": "member_favorite",
            },
        ),
    ]
