# Generated by Django 3.1.3 on 2020-11-10 09:25

import core.constants
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions', '0001_initial')
    ]

    operations = [
        migrations.CreateModel(
            name='MemberBase',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('platform', models.IntegerField(default=core.constants.PlatformType['TRIPRESSO'])),
                ('account', models.CharField(max_length=256)),
                ('surname', models.CharField(max_length=256)),
                ('given_name', models.CharField(max_length=256)),
                ('gender', models.CharField(max_length=256)),
                ('birthday', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
                ('tripresso_coin', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
